### ISSUE TITLE
조회수 (댓글수) 많은 영상에서 무한 로딩 현상

### ISSUE THREAD

**Issue by NaLDo627** [1000ship/poty-web#4]
조회수 혹은 댓글이 엄청 많은 영상의 경우 로딩이 엄청 오래 걸리고 있습니다.
(ex. [강남스타일 뮤직비디오](https://www.youtube.com/watch?v=9bZkp7q19f0))
아마 모든 댓글을 파싱 혹은 API로 가져오는 방식 같은데, 이 부분은 개선이 필요하지 않을까 생각합니다!

Issue URL : http://poty.1000ship.me/#/video/9bZkp7q19f0

**Comment by 1000ship** [comment]
백엔드에서 하이라이트를 추출할 수 없는 영상의 경우, 아무 응답하지 않던 문제
수정.

**Comment by NaLDo627** [comment]
@1000ship 
수정 후 아래와 같이 나옵니다.
![image](https://user-images.githubusercontent.com/36787678/84730027-16df1b00-afd0-11ea-9d04-ff914420f6e6.png)

Issue URL : <http://poty.1000ship.me/#/video/9bZkp7q19f0>
